
<?php include_once('header.php'); ?>            

<h2>Privacy Policy</h2>
<p class="lead-in">Your privacy is important to us. At website.com believe that all individuals should have control and ownership over their personal data.  We feel these <a href="http://www.attentiontrust.org/principles">Principles</a> set out by the Attention Trust provide great guidance in delivering on this committment.</p>
In short:
<ul>
<li>We don&#8217;t share your personal information with anyone except to comply with the law, develop our products, or protect our rights.</li>
<li>We don&#8217;t store personal information on our servers unless required for the on-going operation of one of our services. </li>
</ul>
<p>	Below is our privacy policy which incorporates these goals:</p>
<p>	<a rel="license" href="http://creativecommons.org/licenses/by-sa/2.5/"><img border="0" align="right" alt="Creative Commons License" src="http://creativecommons.org/images/public/somerights20.png" /></a> The great team at <a href="http://automattic.com/privacy/">Wordpress.com</a>have made their Privacy Policy available under a <strong>Creative Commons Sharealike</strong> license, which means you too can use it.</p>

<p>	website.com  (“<strong>website.com</strong>”) operates several websites including <a href="http://www.website.com/">website.com.com</a> and <a href="http://www.website.wordpress.com/">thewebsiteblog.</a> It is website.com’s policy to respect your privacy regarding any information we may collect while operating our websites.</p>
<h3>Website Visitors</h3>
<p>	Like most website operators, website.com collects non-personally-identifying information of the sort that web browsers and servers typically make available, such as the browser type, language preference, referring site, and the date and time of each visitor request. website.com&#8217;s purpose in collecting non-personally identifying information is to better understand how website.com&#8217;s visitors use its website. From time to time, website.com may release non-personally-identifying information in the aggregate, e.g., by publishing a report on trends in the usage of its website.</p>

<p>	website.com also collects potentially personally-identifying information like Internet Protocol (IP) addresses. website.com does not use such information to identify its visitors, however, and does not disclose such information, other than under the same circumstances that it uses and discloses personally-identifying information, as described below.</p>
<h3>Gathering of Personally-Identifying Information</h3>
<p>	Certain visitors to website.com’s websites choose to interact with website.com in ways that require website.com to gather personally-identifying information. The amount and type of information that website.com gathers depends on the nature of the interaction. For example, we ask visitors who sign up for a service at <a href="http://www.website.com/">website.com.com</a> to provide a username and email address. Those who engage in transactions with website.com – by purchasing access to the website.com brand scoring services, for example – are asked to provide additional information, including as necessary the personal and financial information required to process those transactions. In each case, website.com collects such information only insofar as is necessary or appropriate to fulfill the purpose of the visitor’s interaction with website.com. website.com does not disclose personally-identifying information other than as described below. And visitors can always refuse to supply personally-identifying information, with the caveat that it may prevent them from engaging in certain website-related activities.</p>
<h3>Aggregated Statistics</h3>
<p>	website.com may collect statistics about the behavior of visitors to its websites. For instance, website.com may monitor the most popular services on the website.com.com site or use spam screened by the website.com service to help identify spam. website.com may display this information publicly or provide it to others. However, website.com does not disclose personally-identifying information other than as described below.</p>
<h3>Protection of Certain Personally-Identifying Information</h3>

<p>	website.com discloses potentially personally-identifying and personally-identifying information only to those of its employees, contractors and affiliated organizations that (i) need to know that information in order to process it on website.com’s behalf or to provide services available at website.com’s websites, and (ii) that have agreed not to disclose it to others. Some of those employees, contractors and affiliated organizations may be located outside of your home country; by using website.com’s websites, you consent to the transfer of such information to them. website.com will not rent or sell potentially personally-identifying and personally-identifying information to anyone. Other than to its employees, contractors and affiliated organizations, as described above, website.com discloses potentially personally-identifying and personally-identifying information only when required to do so by law, or when website.com believes in good faith that disclosure is reasonably necessary to protect the property or rights of website.com, third parties or the public at large. If you are a registered user of an website.com website and have supplied your email address, website.com may occasionally send you an email to tell you about new features, solicit your feedback, or just keep you up to date with what’s going on with website.com and our products. We primarily use our various services to communicate this type of information, so we expect to keep this type of email to a minimum. If you send us a request (for example via a support email or via one of our feedback mechanisms), we reserve the right to publish it in order to help us clarify or respond to your request or to help us support other users. website.com takes all measures reasonably necessary to protect against the unauthorized access, use, alteration or destruction of potentially personally-identifying and personally-identifying information.</p>
<h3>Cookies</h3>
<p>	A cookie is a string of information that a website stores on a visitor’s computer, and that the visitor’s browser provides to the website each time the visitor returns. website.com uses cookies to help website.com identify and track visitors, their usage of website.com website, and their website access preferences. website.com visitors who do not wish to have cookies placed on their computers should set their browsers to refuse cookies before using website.com’s websites, with the drawback that certain features of website.com’s websites may not function properly without the aid of cookies.</p>
<h3>Privacy Policy Changes</h3>
<p>	Although most changes are likely to be minor, website.com may change its Privacy Policy from time to time, and in website.com’s sole discretion. website.com encourages visitors to frequently check this page for any changes to its Privacy Policy. If you have a website.com.com account, you should also check your services dashboard for alerts to these changes. Your continued use of this site after any change in this Privacy Policy will constitute your acceptance of such change.
</p>

<br />
<br />

<?php include_once ("footer.php"); ?> 
