

CREATE TABLE IF NOT EXISTS `commonadjectives` (
  `commid` int(11) NOT NULL auto_increment,
  `word` varchar(255) NOT NULL,
  PRIMARY KEY  (`commid`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;


INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(1, 'adorable');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(2, 'alert');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(3, 'average');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(4, 'beautiful');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(5, 'blonde');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(6, 'bloody');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(7, 'blushing');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(8, 'bright');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(9, 'clean');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(10, 'clear');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(11, 'cloudy');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(12, 'colourful');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(13, 'concerned');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(14, 'crowded');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(15, 'curious');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(16, 'cute');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(17, 'dark');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(18, 'dirty');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(19, 'drab');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(20, 'distinct');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(21, 'dull');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(22, 'elegant');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(23, 'fancy');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(24, 'filthy');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(25, 'glamorous');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(26, 'gleaming');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(27, 'graceful');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(28, 'grotesque');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(29, 'homely');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(30, 'light');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(31, 'misty');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(32, 'motionless');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(33, 'muddy');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(34, 'plain');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(35, 'poised');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(36, 'quaint');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(37, 'scary');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(38, 'shiny');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(39, 'smoggy');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(40, 'sparkling');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(41, 'spotless');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(42, 'stormy');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(43, 'strange');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(44, 'ugly');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(45, 'unsightly');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(46, 'unusual');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(47, 'alive');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(48, 'brainy');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(49, 'broken');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(50, 'busy');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(51, 'careful');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(52, 'cautious');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(53, 'clever');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(54, 'crazy');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(55, 'damaged');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(56, 'dead');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(57, 'difficult');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(58, 'easy');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(59, 'fake');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(60, 'false');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(61, 'famous');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(62, 'forward');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(63, 'fragile');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(64, 'guilty');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(65, 'helpful');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(66, 'helpless');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(67, 'important');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(68, 'impossible');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(69, 'infamous');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(70, 'innocent');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(71, 'inquisitive');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(72, 'mad');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(73, 'modern');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(74, 'open');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(75, 'outgoing');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(76, 'outstanding');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(77, 'poor');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(78, 'powerful');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(79, 'puzzled');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(80, 'real');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(81, 'rich');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(82, 'right');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(83, 'robust');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(84, 'sane');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(85, 'scary');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(86, 'shy');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(87, 'sleepy');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(88, 'stupid');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(89, 'super');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(90, 'tame');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(91, 'thick');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(92, 'tired');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(93, 'wild');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(94, 'wrong');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(95, 'afraid');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(96, 'angry');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(97, 'annoyed');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(98, 'anxious');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(99, 'arrogant');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(100, 'ashamed');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(101, 'awful');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(102, 'bad');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(103, 'bewildered');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(104, 'bored');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(105, 'concerned');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(106, 'condemned');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(107, 'confused');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(108, 'creepy');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(109, 'cruel');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(110, 'dangerous');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(111, 'defeated');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(112, 'defiant');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(113, 'depressed');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(114, 'disgusted');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(115, 'disturbed');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(116, 'doubtful');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(117, 'eerie');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(118, 'embarrassed');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(119, 'envious');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(120, 'evil');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(121, 'fierce');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(122, 'foolish');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(123, 'frantic');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(124, 'frightened');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(125, 'grieving');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(126, 'guilty');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(127, 'helpless');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(128, 'hungry');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(129, 'hurt');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(130, 'ill');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(131, 'jealous');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(132, 'lonely');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(133, 'mad');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(134, 'naughty');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(135, 'nervous');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(136, 'obnoxious');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(137, 'outrageous');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(138, 'panicky');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(139, 'repulsive');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(140, 'safe');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(141, 'scared');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(142, 'shy');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(143, 'sleepy');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(144, 'sore');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(145, 'strange');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(146, 'tense');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(147, 'terrible');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(148, 'tired');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(149, 'troubled');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(150, 'unusual');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(151, 'upset');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(152, 'uptight');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(153, 'weary');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(154, 'wicked');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(155, 'worried');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(156, 'broad');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(157, 'crooked');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(158, 'curved');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(159, 'deep');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(160, 'even');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(161, 'flat');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(162, 'hilly');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(163, 'jagged');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(164, 'round');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(165, 'shallow');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(166, 'square');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(167, 'steep');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(168, 'straight');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(169, 'thick');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(170, 'thin');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(171, 'triangular');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(172, 'uneven');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(173, 'average');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(174, 'big');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(175, 'fat');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(176, 'gigantic');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(177, 'huge');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(178, 'large');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(179, 'little');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(180, 'long');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(181, 'massive');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(182, 'medium');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(183, 'miniature');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(184, 'narrow');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(185, 'petite');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(186, 'short');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(187, 'skinny');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(188, 'small');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(189, 'tall');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(190, 'tiny');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(191, 'wide');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(192, 'cooing');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(193, 'deafening');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(194, 'faint');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(195, 'harsh');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(196, 'high-pitched');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(197, 'hissing');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(198, 'hushed');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(199, 'husky');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(200, 'loud');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(201, 'melodic');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(202, 'moaning');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(203, 'mute');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(204, 'noisy');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(205, 'purring');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(206, 'quiet');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(207, 'raspy');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(208, 'screeching');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(209, 'shrill');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(210, 'silent');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(211, 'soft');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(212, 'squeaky');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(213, 'squealing');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(214, 'thundering');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(215, 'voiceless');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(216, 'whispering');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(217, 'alright');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(218, 'calm');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(219, 'different');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(220, 'fair');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(221, 'fine');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(222, 'OK');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(223, 'pleasant');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(224, 'puzzled');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(225, 'agreeable');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(226, 'alert');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(227, 'amused');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(228, 'brave');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(229, 'bright');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(230, 'charming');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(231, 'cheerful');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(232, 'comfortable');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(233, 'cooperative');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(234, 'courageous');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(235, 'delightful');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(236, 'determined');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(237, 'eager');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(238, 'elated');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(239, 'enchanting');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(240, 'encouraging');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(241, 'energetic');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(242, 'enthusiastic');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(243, 'excited');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(244, 'exuberant');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(245, 'faithful');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(246, 'fantastic');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(247, 'friendly');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(248, 'frowning');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(249, 'funny');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(250, 'gentle');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(251, 'glorious');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(252, 'good');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(253, 'happy');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(254, 'healthy');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(255, 'helpful');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(256, 'hilarious');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(257, 'innocent');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(258, 'jolly');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(259, 'kind');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(260, 'lively');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(261, 'lovely');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(262, 'lucky');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(263, 'obedient');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(264, 'perfect');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(265, 'proud');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(266, 'relaxed');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(267, 'relieved');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(268, 'silly');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(269, 'smiling');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(270, 'splendid');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(271, 'successful');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(272, 'thoughtful');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(273, 'victorious');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(274, 'vivacious');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(275, 'well');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(276, 'witty');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(277, 'wonderful');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(278, 'fast');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(279, 'quick');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(280, 'rapid');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(281, 'slow');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(282, 'swift');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(283, 'bitter');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(284, 'bland');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(285, 'delicious');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(286, 'different');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(287, 'fresh');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(288, 'greasy');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(289, 'hot');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(290, 'juicy');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(291, 'repulsive');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(292, 'revolting');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(293, 'ripe');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(294, 'rotten');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(295, 'salty');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(296, 'sour');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(297, 'spicy');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(298, 'stale');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(299, 'strong');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(300, 'sweet');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(301, 'tasteless');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(302, 'tasty');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(303, 'terrible');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(304, 'wonderful');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(305, 'ancient');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(306, 'brief');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(307, 'early');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(308, 'late');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(309, 'long');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(310, 'modern');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(311, 'new');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(312, 'old');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(313, 'old-fashioned');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(314, 'quick');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(315, 'short');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(316, 'young');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(317, 'blunt');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(318, 'boiling');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(319, 'breakable');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(320, 'breezy');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(321, 'broken');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(322, 'bumpy');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(323, 'chilly');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(324, 'clean');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(325, 'cold');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(326, 'cool');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(327, 'crooked');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(328, 'cuddly');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(329, 'curly');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(330, 'damaged');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(331, 'damp');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(332, 'different');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(333, 'dirty');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(334, 'dry');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(335, 'dusty');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(336, 'filthy');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(337, 'flaky');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(338, 'fluffy');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(339, 'fuzzy');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(340, 'greasy');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(341, 'grubby');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(342, 'hard');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(343, 'icy');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(344, 'loose');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(345, 'plastic');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(346, 'prickly');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(347, 'ripe');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(348, 'rough');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(349, 'rubbery');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(350, 'scratchy');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(351, 'shaky');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(352, 'shaggy');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(353, 'sharp');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(354, 'silky');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(355, 'slimy');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(356, 'slippery');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(357, 'smooth');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(358, 'soft');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(359, 'solid');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(360, 'steady');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(361, 'sticky');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(362, 'tight');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(363, 'uneven');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(364, 'unusual');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(365, 'unripe');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(366, 'warm');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(367, 'weak');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(368, 'wet');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(369, 'wooden');
INSERT INTO `commonadjectives` (`commid`, `word`) VALUES(370, 'woo');


CREATE TABLE IF NOT EXISTS `commonverbs` (
  `comvid` int(11) NOT NULL auto_increment,
  `word` varchar(255) NOT NULL,
  PRIMARY KEY  (`comvid`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;


INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(1, 'accept');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(2, 'add');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(3, 'admire');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(4, 'admit');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(5, 'advise');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(6, 'afford');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(7, 'agree');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(8, 'alert');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(9, 'allow');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(10, 'amuse');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(11, 'analyse');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(12, 'announce');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(13, 'annoy');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(14, 'answer');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(15, 'apologise');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(16, 'appear');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(17, 'applaud');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(18, 'appreciate');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(19, 'approve');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(20, 'argue');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(21, 'arrange');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(22, 'arrest');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(23, 'arrive');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(24, 'ask');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(25, 'attach');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(26, 'attack');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(27, 'attempt');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(28, 'attend');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(29, 'attract');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(30, 'avoid');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(31, 'back');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(32, 'bake');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(33, 'balance');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(34, 'ban');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(35, 'bang');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(36, 'bare');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(37, 'bat');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(38, 'bathe');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(39, 'battle');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(40, 'beam');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(41, 'beg');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(42, 'behave');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(43, 'belong');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(44, 'bleach');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(45, 'bless');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(46, 'blind');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(47, 'blink');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(48, 'blot');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(49, 'blush');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(50, 'boast');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(51, 'boil');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(52, 'bolt');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(53, 'bomb');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(54, 'book');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(55, 'bore');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(56, 'borrow');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(57, 'bounce');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(58, 'bow');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(59, 'box');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(60, 'brake');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(61, 'brake');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(62, 'branch');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(63, 'breathe');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(64, 'bruise');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(65, 'brush');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(66, 'bubble');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(67, 'bump');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(68, 'burn');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(69, 'bury');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(70, 'buzz');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(71, 'calculate');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(72, 'call');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(73, 'camp');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(74, 'care');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(75, 'carry');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(76, 'carve');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(77, 'cause');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(78, 'challenge');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(79, 'change');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(80, 'charge');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(81, 'chase');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(82, 'cheat');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(83, 'check');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(84, 'cheer');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(85, 'chew');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(86, 'choke');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(87, 'chop');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(88, 'claim');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(89, 'clap');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(90, 'clean');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(91, 'clear');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(92, 'clip');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(93, 'close');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(94, 'coach');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(95, 'coil');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(96, 'collect');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(97, 'colour');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(98, 'comb');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(99, 'command');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(100, 'communicate');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(101, 'compare');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(102, 'compete');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(103, 'complain');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(104, 'complete');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(105, 'concentrate');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(106, 'concern');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(107, 'confess');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(108, 'confuse');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(109, 'connect');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(110, 'consider');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(111, 'consist');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(112, 'contain');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(113, 'continue');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(114, 'copy');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(115, 'correct');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(116, 'cough');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(117, 'count');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(118, 'cover');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(119, 'crack');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(120, 'crash');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(121, 'crawl');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(122, 'cross');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(123, 'crush');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(124, 'cry');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(125, 'cure');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(126, 'curl');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(127, 'curve');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(128, 'cycle');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(129, 'dam');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(130, 'damage');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(131, 'dance');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(132, 'dare');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(133, 'decay');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(134, 'deceive');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(135, 'decide');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(136, 'decorate');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(137, 'delay');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(138, 'delight');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(139, 'deliver');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(140, 'depend');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(141, 'describe');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(142, 'desert');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(143, 'deserve');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(144, 'destroy');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(145, 'detect');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(146, 'develop');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(147, 'disagree');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(148, 'disappear');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(149, 'disapprove');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(150, 'disarm');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(151, 'discover');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(152, 'dislike');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(153, 'divide');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(154, 'double');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(155, 'doubt');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(156, 'drag');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(157, 'drain');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(158, 'dream');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(159, 'dress');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(160, 'drip');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(161, 'drop');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(162, 'drown');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(163, 'drum');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(164, 'dry');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(165, 'dust');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(166, 'earn');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(167, 'educate');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(168, 'embarrass');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(169, 'employ');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(170, 'empty');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(171, 'encourage');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(172, 'end');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(173, 'enjoy');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(174, 'enter');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(175, 'entertain');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(176, 'escape');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(177, 'examine');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(178, 'excite');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(179, 'excuse');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(180, 'exercise');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(181, 'exist');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(182, 'expand');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(183, 'expect');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(184, 'explain');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(185, 'explode');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(186, 'extend');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(187, 'face');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(188, 'fade');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(189, 'fail');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(190, 'fancy');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(191, 'fasten');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(192, 'fax');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(193, 'fear');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(194, 'fence');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(195, 'fetch');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(196, 'file');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(197, 'fill');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(198, 'film');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(199, 'fire');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(200, 'fit');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(201, 'fix');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(202, 'flap');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(203, 'flash');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(204, 'float');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(205, 'flood');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(206, 'flow');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(207, 'flower');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(208, 'fold');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(209, 'follow');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(210, 'fool');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(211, 'force');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(212, 'form');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(213, 'found');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(214, 'frame');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(215, 'frighten');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(216, 'fry');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(217, 'gather');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(218, 'gaze');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(219, 'glow');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(220, 'glue');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(221, 'grab');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(222, 'grate');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(223, 'grease');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(224, 'greet');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(225, 'grin');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(226, 'grip');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(227, 'groan');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(228, 'guarantee');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(229, 'guard');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(230, 'guess');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(231, 'guide');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(232, 'hammer');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(233, 'hand');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(234, 'handle');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(235, 'hang');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(236, 'happen');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(237, 'harass');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(238, 'harm');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(239, 'hate');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(240, 'haunt');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(241, 'head');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(242, 'heal');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(243, 'heap');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(244, 'heat');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(245, 'help');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(246, 'hook');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(247, 'hop');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(248, 'hope');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(249, 'hover');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(250, 'hug');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(251, 'hum');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(252, 'hunt');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(253, 'hurry');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(254, 'identify');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(255, 'ignore');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(256, 'imagine');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(257, 'impress');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(258, 'improve');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(259, 'include');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(260, 'increase');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(261, 'influence');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(262, 'inform');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(263, 'inject');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(264, 'injure');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(265, 'instruct');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(266, 'intend');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(267, 'interest');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(268, 'interfere');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(269, 'interrupt');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(270, 'introduce');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(271, 'invent');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(272, 'invite');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(273, 'irritate');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(274, 'itch');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(275, 'jail');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(276, 'jam');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(277, 'jog');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(278, 'join');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(279, 'joke');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(280, 'judge');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(281, 'juggle');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(282, 'jump');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(283, 'kick');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(284, 'kill');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(285, 'kiss');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(286, 'kneel');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(287, 'knit');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(288, 'knock');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(289, 'knot');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(290, 'label');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(291, 'land');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(292, 'last');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(293, 'laugh');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(294, 'launch');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(295, 'learn');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(296, 'level');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(297, 'license');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(298, 'lick');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(299, 'lie');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(300, 'lighten');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(301, 'like');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(302, 'list');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(303, 'listen');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(304, 'live');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(305, 'load');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(306, 'lock');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(307, 'long');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(308, 'look');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(309, 'love');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(310, 'man');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(311, 'manage');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(312, 'march');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(313, 'mark');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(314, 'marry');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(315, 'match');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(316, 'mate');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(317, 'matter');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(318, 'measure');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(319, 'meddle');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(320, 'melt');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(321, 'memorise');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(322, 'mend');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(323, 'messup');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(324, 'milk');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(325, 'mine');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(326, 'miss');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(327, 'mix');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(328, 'moan');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(329, 'moor');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(330, 'mourn');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(331, 'move');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(332, 'muddle');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(333, 'mug');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(334, 'multiply');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(335, 'murder');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(336, 'nail');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(337, 'name');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(338, 'need');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(339, 'nest');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(340, 'nod');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(341, 'note');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(342, 'notice');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(343, 'number');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(344, 'obey');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(345, 'object');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(346, 'observe');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(347, 'obtain');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(348, 'occur');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(349, 'offend');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(350, 'offer');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(351, 'open');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(352, 'order');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(353, 'overflow');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(354, 'owe');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(355, 'own');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(356, 'pack');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(357, 'paddle');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(358, 'paint');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(359, 'park');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(360, 'part');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(361, 'pass');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(362, 'paste');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(363, 'pat');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(364, 'pause');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(365, 'peck');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(366, 'pedal');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(367, 'peel');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(368, 'peep');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(369, 'perform');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(370, 'permit');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(371, 'phone');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(372, 'pick');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(373, 'pinch');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(374, 'pine');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(375, 'place');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(376, 'plan');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(377, 'plant');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(378, 'play');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(379, 'please');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(380, 'plug');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(381, 'point');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(382, 'poke');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(383, 'polish');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(384, 'pop');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(385, 'possess');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(386, 'post');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(387, 'pour');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(388, 'practise');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(389, 'pray');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(390, 'preach');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(391, 'precede');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(392, 'prefer');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(393, 'prepare');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(394, 'present');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(395, 'preserve');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(396, 'press');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(397, 'pretend');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(398, 'prevent');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(399, 'prick');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(400, 'print');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(401, 'produce');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(402, 'program');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(403, 'promise');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(404, 'protect');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(405, 'provide');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(406, 'pull');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(407, 'pump');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(408, 'punch');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(409, 'puncture');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(410, 'punish');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(411, 'push');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(412, 'question');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(413, 'queue');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(414, 'race');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(415, 'radiate');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(416, 'rain');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(417, 'raise');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(418, 'reach');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(419, 'realise');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(420, 'receive');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(421, 'recognise');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(422, 'record');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(423, 'reduce');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(424, 'reflect');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(425, 'refuse');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(426, 'regret');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(427, 'reign');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(428, 'reject');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(429, 'rejoice');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(430, 'relax');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(431, 'release');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(432, 'rely');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(433, 'remain');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(434, 'remember');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(435, 'remind');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(436, 'remove');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(437, 'repair');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(438, 'repeat');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(439, 'replace');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(440, 'reply');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(441, 'report');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(442, 'reproduce');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(443, 'request');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(444, 'rescue');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(445, 'retire');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(446, 'return');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(447, 'rhyme');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(448, 'rinse');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(449, 'risk');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(450, 'rob');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(451, 'rock');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(452, 'roll');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(453, 'rot');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(454, 'rub');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(455, 'ruin');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(456, 'rule');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(457, 'rush');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(458, 'sack');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(459, 'sail');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(460, 'satisfy');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(461, 'save');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(462, 'saw');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(463, 'scare');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(464, 'scatter');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(465, 'scold');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(466, 'scorch');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(467, 'scrape');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(468, 'scratch');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(469, 'scream');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(470, 'screw');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(471, 'scribble');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(472, 'scrub');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(473, 'seal');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(474, 'search');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(475, 'separate');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(476, 'serve');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(477, 'settle');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(478, 'shade');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(479, 'share');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(480, 'shave');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(481, 'shelter');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(482, 'shiver');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(483, 'shock');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(484, 'shop');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(485, 'shrug');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(486, 'sigh');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(487, 'sign');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(488, 'signal');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(489, 'sin');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(490, 'sip');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(491, 'ski');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(492, 'skip');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(493, 'slap');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(494, 'slip');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(495, 'slow');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(496, 'smash');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(497, 'smell');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(498, 'smile');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(499, 'smoke');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(500, 'snatch');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(501, 'sneeze');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(502, 'sniff');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(503, 'snore');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(504, 'snow');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(505, 'soak');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(506, 'soothe');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(507, 'sound');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(508, 'spare');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(509, 'spark');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(510, 'sparkle');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(511, 'spell');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(512, 'spill');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(513, 'spoil');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(514, 'spot');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(515, 'spray');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(516, 'sprout');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(517, 'squash');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(518, 'squeak');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(519, 'squeal');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(520, 'squeeze');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(521, 'stain');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(522, 'stamp');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(523, 'stare');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(524, 'start');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(525, 'stay');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(526, 'steer');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(527, 'step');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(528, 'stir');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(529, 'stitch');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(530, 'stop');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(531, 'store');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(532, 'strap');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(533, 'strengthen');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(534, 'stretch');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(535, 'strip');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(536, 'stroke');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(537, 'stuff');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(538, 'subtract');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(539, 'succeed');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(540, 'suck');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(541, 'suffer');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(542, 'suggest');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(543, 'suit');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(544, 'supply');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(545, 'support');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(546, 'suppose');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(547, 'surprise');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(548, 'surround');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(549, 'suspect');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(550, 'suspend');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(551, 'switch');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(552, 'talk');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(553, 'tame');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(554, 'tap');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(555, 'taste');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(556, 'tease');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(557, 'telephone');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(558, 'tempt');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(559, 'terrify');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(560, 'test');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(561, 'thank');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(562, 'thaw');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(563, 'tick');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(564, 'tickle');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(565, 'tie');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(566, 'time');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(567, 'tip');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(568, 'tire');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(569, 'touch');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(570, 'tour');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(571, 'tow');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(572, 'trace');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(573, 'trade');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(574, 'train');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(575, 'transport');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(576, 'trap');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(577, 'travel');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(578, 'treat');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(579, 'tremble');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(580, 'trick');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(581, 'trip');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(582, 'trot');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(583, 'trouble');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(584, 'trust');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(585, 'try');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(586, 'tug');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(587, 'tumble');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(588, 'turn');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(589, 'twist');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(590, 'type');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(591, 'undress');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(592, 'unfasten');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(593, 'unite');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(594, 'unlock');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(595, 'unpack');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(596, 'untidy');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(597, 'use');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(598, 'vanish');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(599, 'visit');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(600, 'wail');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(601, 'wait');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(602, 'walk');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(603, 'wander');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(604, 'want');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(605, 'warm');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(606, 'warn');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(607, 'wash');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(608, 'waste');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(609, 'watch');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(610, 'water');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(611, 'wave');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(612, 'weigh');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(613, 'welcome');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(614, 'whine');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(615, 'whip');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(616, 'whirl');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(617, 'whisper');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(618, 'whistle');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(619, 'wink');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(620, 'wipe');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(621, 'wish');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(622, 'wobble');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(623, 'wonder');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(624, 'work');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(625, 'worry');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(626, 'wrap');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(627, 'wreck');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(628, 'wrestle');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(629, 'wriggle');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(630, 'x-ray');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(631, 'yawn');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(632, 'yell');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(633, 'zip');
INSERT INTO `commonverbs` (`comvid`, `word`) VALUES(634, 'zo');


CREATE TABLE IF NOT EXISTS `conjunctions` (
  `conjid` int(11) NOT NULL auto_increment,
  `word` varchar(255) NOT NULL,
  PRIMARY KEY  (`conjid`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;


INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(1, 'and');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(2, 'after');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(3, 'although');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(4, 'as');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(5, 'but');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(6, 'soon');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(7, 'because');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(8, 'before');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(9, 'time');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(10, 'even');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(11, 'if');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(12, 'though');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(13, 'every');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(14, 'if');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(15, 'case');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(16, 'in');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(17, 'event');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(18, 'than');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(19, 'just');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(20, 'case');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(21, 'now');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(22, 'that');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(23, 'not');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(24, 'once');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(25, 'only');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(26, 'or');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(27, 'since');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(28, 'first');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(29, 'though');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(30, 'unless');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(31, 'until');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(32, 'there');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(33, 'til');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(34, 'till');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(35, 'when ');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(36, 'whenever');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(37, 'whereas');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(38, 'whether');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(39, 'while');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(40, 'lest');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(41, 'inasmuch');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(42, 'why');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(43, 'so');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(44, 'ok');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(45, 'please');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(46, 'how');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(47, 'more');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(48, 'less');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(49, 'fewer');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(50, 'often');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(51, 'most');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(52, 'here');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(53, 'there');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(54, 'early');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(55, 'late');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(56, 'enough');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(57, 'sufficient');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(58, 'such');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(59, 'already');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(60, 'yet');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(61, 'those');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(62, 'these');
INSERT INTO `conjunctions` (`conjid`, `word`) VALUES(63, 'th');


CREATE TABLE IF NOT EXISTS `determiners` (
  `detid` int(11) NOT NULL auto_increment,
  `word` varchar(255) NOT NULL,
  PRIMARY KEY  (`detid`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;


INSERT INTO `determiners` (`detid`, `word`) VALUES(1, 'the');
INSERT INTO `determiners` (`detid`, `word`) VALUES(2, 'a ');
INSERT INTO `determiners` (`detid`, `word`) VALUES(3, 'an ');
INSERT INTO `determiners` (`detid`, `word`) VALUES(4, 'another ');
INSERT INTO `determiners` (`detid`, `word`) VALUES(5, 'no ');
INSERT INTO `determiners` (`detid`, `word`) VALUES(10, 'another ');
INSERT INTO `determiners` (`detid`, `word`) VALUES(11, 'some ');
INSERT INTO `determiners` (`detid`, `word`) VALUES(12, 'any ');
INSERT INTO `determiners` (`detid`, `word`) VALUES(13, 'my ');
INSERT INTO `determiners` (`detid`, `word`) VALUES(14, 'our ');
INSERT INTO `determiners` (`detid`, `word`) VALUES(15, 'their ');
INSERT INTO `determiners` (`detid`, `word`) VALUES(16, 'her ');
INSERT INTO `determiners` (`detid`, `word`) VALUES(17, 'his ');
INSERT INTO `determiners` (`detid`, `word`) VALUES(18, 'its ');
INSERT INTO `determiners` (`detid`, `word`) VALUES(19, 'another ');
INSERT INTO `determiners` (`detid`, `word`) VALUES(21, 'each ');
INSERT INTO `determiners` (`detid`, `word`) VALUES(22, 'every ');
INSERT INTO `determiners` (`detid`, `word`) VALUES(23, 'certain ');
INSERT INTO `determiners` (`detid`, `word`) VALUES(24, 'its ');
INSERT INTO `determiners` (`detid`, `word`) VALUES(25, 'another ');
INSERT INTO `determiners` (`detid`, `word`) VALUES(27, 'this ');
INSERT INTO `determiners` (`detid`, `word`) VALUES(28, 'tha');



CREATE TABLE IF NOT EXISTS `irregularverbs` (
  `irrid` int(11) NOT NULL auto_increment,
  `word` varchar(255) NOT NULL,
  PRIMARY KEY  (`irrid`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;


INSERT INTO `irregularverbs` (`irrid`, `word`) VALUES(4, 'am');
INSERT INTO `irregularverbs` (`irrid`, `word`) VALUES(5, 'are');
INSERT INTO `irregularverbs` (`irrid`, `word`) VALUES(6, 'is');
INSERT INTO `irregularverbs` (`irrid`, `word`) VALUES(7, 'be');
INSERT INTO `irregularverbs` (`irrid`, `word`) VALUES(8, 'was');
INSERT INTO `irregularverbs` (`irrid`, `word`) VALUES(9, 'were');
INSERT INTO `irregularverbs` (`irrid`, `word`) VALUES(10, 'been');
INSERT INTO `irregularverbs` (`irrid`, `word`) VALUES(57, 'do ');
INSERT INTO `irregularverbs` (`irrid`, `word`) VALUES(58, 'did ');
INSERT INTO `irregularverbs` (`irrid`, `word`) VALUES(98, 'get');
INSERT INTO `irregularverbs` (`irrid`, `word`) VALUES(99, 'got ');
INSERT INTO `irregularverbs` (`irrid`, `word`) VALUES(112, 'has');
INSERT INTO `irregularverbs` (`irrid`, `word`) VALUES(113, 'have ');
INSERT INTO `irregularverbs` (`irrid`, `word`) VALUES(114, 'had ');
INSERT INTO `irregularverbs` (`irrid`, `word`) VALUES(194, 'take ');



CREATE TABLE IF NOT EXISTS `prepositions` (
  `prepid` int(11) NOT NULL auto_increment,
  `word` varchar(255) NOT NULL,
  PRIMARY KEY  (`prepid`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;


INSERT INTO `prepositions` (`prepid`, `word`) VALUES(1, 'aboard');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(2, 'about');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(3, 'above');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(4, 'absent');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(5, 'according');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(6, 'across');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(7, 'after ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(8, 'against ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(9, 'ahead');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(10, 'all');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(11, 'along ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(12, 'alongside ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(13, 'amid');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(14, 'amidst ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(15, 'among ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(16, 'around ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(17, 'as ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(18, 'aside ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(19, 'astride ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(20, 'at ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(21, 'away');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(22, 'bar ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(23, 'barring ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(24, 'because');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(25, 'before ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(26, 'behind ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(27, 'below ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(28, 'beneath ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(29, 'beside ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(30, 'besides ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(31, 'between ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(32, 'beyond ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(33, 'but ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(34, 'by');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(35, 'circa ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(36, 'close');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(37, 'concerning ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(38, 'considering ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(39, 'despite ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(40, 'down ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(41, 'due');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(42, 'during');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(43, 'except ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(44, 'excepting ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(45, 'excluding ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(46, 'failing ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(47, 'for ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(48, 'from ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(49, 'in ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(50, 'including ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(51, 'inside ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(52, 'instead');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(53, 'into ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(54, 'less ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(55, 'like ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(56, 'minus ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(57, 'near ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(58, 'next');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(59, 'notwithstanding ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(60, 'of ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(61, 'off ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(62, 'on');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(63, 'onto ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(64, 'opposite ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(65, 'out ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(66, 'outside ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(67, 'over ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(68, 'past ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(69, 'pending ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(70, 'per ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(71, 'plus ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(72, 'regarding ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(73, 'respecting ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(74, 'round ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(75, 'save ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(76, 'saving ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(77, 'similar');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(78, 'since ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(79, 'than ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(80, 'through ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(81, 'throughout ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(82, 'till ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(83, 'to ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(84, 'toward');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(85, 'towards ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(86, 'under ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(87, 'underneath ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(88, 'unlike ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(89, 'until ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(90, 'unto ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(91, 'up ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(92, 'upon ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(93, 'versus ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(94, 'via ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(95, 'wanting ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(96, 'while ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(97, 'with ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(98, 'within ');
INSERT INTO `prepositions` (`prepid`, `word`) VALUES(99, 'withou');



CREATE TABLE IF NOT EXISTS `pronouns` (
  `pronid` int(11) NOT NULL auto_increment,
  `word` varchar(255) NOT NULL,
  PRIMARY KEY  (`pronid`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;


INSERT INTO `pronouns` (`pronid`, `word`) VALUES(1, 'all');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(2, 'another');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(3, 'any');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(4, 'anybody');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(5, 'anyone');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(6, 'anything');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(7, 'both');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(8, 'each');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(9, 'either');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(10, 'everybody');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(11, 'everyone');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(12, 'everything');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(13, 'few');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(14, 'he');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(15, 'her');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(16, 'hers');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(17, 'herself');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(18, 'him');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(19, 'himself');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(20, 'his');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(21, 'I');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(22, 'it');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(23, 'its');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(24, 'itself');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(25, 'many');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(26, 'me');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(27, 'mine');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(28, 'my');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(29, 'myself');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(30, 'neither');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(31, 'no one');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(32, 'nobody');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(33, 'none');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(34, 'nothing');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(35, 'one');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(36, 'others');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(37, 'our');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(38, 'ours');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(39, 'ourselves');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(40, 'she');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(41, 'some');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(42, 'somebody');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(43, 'someone');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(44, 'something');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(45, 'that');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(46, 'their');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(47, 'theirs');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(48, 'them');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(49, 'themselves');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(50, 'these');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(51, 'they');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(52, 'this');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(53, 'us');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(54, 'we');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(55, 'what');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(56, 'which');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(57, 'who');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(58, 'whom');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(59, 'whose');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(60, 'you');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(61, 'your');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(62, 'yours');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(63, 'yourself');
INSERT INTO `pronouns` (`pronid`, `word`) VALUES(64, 'yourselves');


CREATE TABLE IF NOT EXISTS `wordtypes` (
  `wordtypeid` int(11) NOT NULL auto_increment,
  `wordtype` varchar(255) NOT NULL,
  PRIMARY KEY  (`wordtypeid`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;


INSERT INTO `wordtypes` (`wordtypeid`, `wordtype`) VALUES(1, 'commonadjectives');
INSERT INTO `wordtypes` (`wordtypeid`, `wordtype`) VALUES(2, 'commonverbs');
INSERT INTO `wordtypes` (`wordtypeid`, `wordtype`) VALUES(3, 'conjunctions');
INSERT INTO `wordtypes` (`wordtypeid`, `wordtype`) VALUES(4, 'determiners');
INSERT INTO `wordtypes` (`wordtypeid`, `wordtype`) VALUES(5, 'irregularverbs');
INSERT INTO `wordtypes` (`wordtypeid`, `wordtype`) VALUES(6, 'prepositions');
INSERT INTO `wordtypes` (`wordtypeid`, `wordtype`) VALUES(7, 'pronouns');